<?php

namespace App\Admin\Controllers;

use App\Models\Admin\Permission as CheckPermission;
use Illuminate\Routing\Controller;


class BaseController extends Controller
{
    protected $seg2;
    protected $seg3;

    public function callAction($method, $parameters)
    {
        $this->seg2 = \Request::segment(2);
        $this->seg3 = \Request::segment(3);
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    /**
     * Index interface.
     *
     * @return Content
     */
    public function index()
    {
        if (!\Admin::user()->isRole('administrator')) {
            $uri = $this->seg2 . '/' . $this->seg3;
            CheckPermission::hasMenu($uri);
        }
    }

    /**
     * Edit interface.
     *
     * @param $id
     *
     * @return Content
     */
    public function edit($id)
    {
        if (!\Admin::user()->isRole('administrator')) {
            $uri = $this->seg2 . '/' . $this->seg3;
            CheckPermission::hasMenu($uri);
            CheckPermission::check('update');
        }
    }

    /**
     * Create interface.
     *
     * @return Content
     */
    public function create()
    {
        if (!\Admin::user()->isRole('administrator')) {
            $uri = $this->seg2 . '/' . $this->seg3;
            CheckPermission::hasMenu($uri);
            CheckPermission::check('insert');
        }
    }


}
